ERROR 2020-12-25 14:51:25,657 root : Unable to conect to the server: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /health (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f3c962c5c40>: Failed to establish a new connection: [Errno 111] Connection refused'))
INFO 2020-12-25 14:51:45,799 root : Сервер доступний. Час на сервері: 2020-12-25T14:51:45.797545
INFO 2020-12-25 14:51:45,799 root : Запитувана сторінка: : http://localhost:8000/health/
INFO 2020-12-25 14:51:45,799 root : Відповідь сервера місти наступні поля:
INFO 2020-12-25 14:51:45,799 root : Ключ: servername, Значення: lab server
INFO 2020-12-25 14:51:45,799 root : Ключ: random, Значення: 33
INFO 2020-12-25 14:51:45,799 root : Ключ: datetime, Значення: 2020-12-25T14:51:45.797545
INFO 2020-12-25 14:51:45,799 root : Ключ: server_url, Значення: http://localhost:8000/health/
INFO 2020-12-25 14:51:45,800 root : Ключ: server_iinfo, Значення: {'system': 'posix', 'srv_pid': 12}
INFO 2020-12-25 14:51:45,800 root : Ключ: client_info, Значення: {'user agent': 'python-requests/2.25.0', 'remote addr': '127.0.0.1', 'remote host': ''}
INFO 2020-12-25 14:52:45,852 root : Сервер доступний. Час на сервері: 2020-12-25T14:52:45.852087
INFO 2020-12-25 14:52:45,852 root : Запитувана сторінка: : http://localhost:8000/health/
INFO 2020-12-25 14:52:45,853 root : Відповідь сервера місти наступні поля:
INFO 2020-12-25 14:52:45,853 root : Ключ: servername, Значення: lab server
INFO 2020-12-25 14:52:45,853 root : Ключ: random, Значення: 139
INFO 2020-12-25 14:52:45,853 root : Ключ: datetime, Значення: 2020-12-25T14:52:45.852087
INFO 2020-12-25 14:52:45,853 root : Ключ: server_url, Значення: http://localhost:8000/health/
INFO 2020-12-25 14:52:45,853 root : Ключ: server_iinfo, Значення: {'system': 'posix', 'srv_pid': 12}
INFO 2020-12-25 14:52:45,853 root : Ключ: client_info, Значення: {'user agent': 'python-requests/2.25.0', 'remote addr': '127.0.0.1', 'remote host': ''}
